pipeline {
    agent {
        docker {
            image 'kafziel4/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation') {
            steps {
                sh 'cd web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd web && rake local_seeds'   
            }
        }
        stage('UAT') {
            steps {
                echo 'Aguardando testes de aceitação.'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Production') {
            steps {
                echo 'WebApp pronta para produção :)'
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'web/logs']]
        }
    }
}